name: Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: ['*']

jobs:
  compute-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.result }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v5
        id: changes
        with:
          script: return await require('./.github/workflows/scripts/build-matrix.js')({github, context});

  test:
    runs-on: ubuntu-latest
    name: 'Tests: ${{ matrix.changes.name }}'
    needs: [ compute-changes ]
    environment: Testing
    strategy:
      matrix:
        changes: ${{ fromJson(needs.compute-changes.outputs.changes).all }}
    steps:
      - uses: actions/checkout@v2
      - run: ${{ matrix.changes.commandPrefix }} install
        working-directory: ${{ matrix.changes.codebasePath }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}
          TF_STATE_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: ${{ matrix.changes.commandPrefix }} test
        working-directory: ${{ matrix.changes.codebasePath }}

  lint:
    runs-on: ubuntu-latest
    name: 'Linting: ${{ matrix.changes.name }}'
    needs: [ compute-changes ]
    environment: Testing
    strategy:
      matrix:
        changes: ${{ fromJson(needs.compute-changes.outputs.changes).all }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        if: ${{ matrix.changes.hasInfrastructure }}
        with:
          terraform_version: 1.1.2
      - uses: terraform-linters/setup-tflint@v1
        if: ${{ matrix.changes.hasInfrastructure }}
      - run: ${{ matrix.changes.commandPrefix }} install
        working-directory: ${{ matrix.changes.codebasePath }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}
          TF_STATE_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: ${{ matrix.changes.commandPrefix }} lint
        working-directory: ${{ matrix.changes.codebasePath }}

  build:
    runs-on: ubuntu-latest
    name: 'Build: ${{ matrix.changes.name }}'
    needs: [ compute-changes ]
    environment: Testing
    strategy:
      matrix:
        changes: ${{ fromJson(needs.compute-changes.outputs.changes).all }}
    steps:
      - uses: actions/checkout@v2
      - run: ${{ matrix.changes.commandPrefix }} install
        working-directory: ${{ matrix.changes.codebasePath }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}
          TF_STATE_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: ${{ matrix.changes.commandPrefix }} build
        working-directory: ${{ matrix.changes.codebasePath }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.changes.name }}
          path: ${{ matrix.changes.codebasePath }}/build/**
          if-no-files-found: ignore

  deploy-infrastructure-testing:
    runs-on: ubuntu-latest
    name: 'Deploy (Testing): Infrastructure'
    needs: [ compute-changes, test, build, lint ]
    environment: Testing
    concurrency: Testing
    if: ${{ fromJson(needs.compute-changes.outputs.changes).infrastructure }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.2
      - run: ${{ fromJson(needs.compute-changes.outputs.changes).infrastructure.commandPrefix }} install
        working-directory: ${{ fromJson(needs.compute-changes.outputs.changes).infrastructure.codebasePath }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}
          TF_STATE_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: ${{ fromJson(needs.compute-changes.outputs.changes).infrastructure.commandPrefix }} deploy
        working-directory: ${{ fromJson(needs.compute-changes.outputs.changes).infrastructure.codebasePath }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}
          TF_STATE_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_VAR_environment: ${{ secrets.ENVIRONMENT }}
          TF_VAR_system: ${{ secrets.SYSTEM }}

  deploy-apps-testing:
    runs-on: ubuntu-latest
    name: 'Deploy (Testing): ${{ matrix.changes.name }}'
    needs: [ compute-changes, deploy-infrastructure-testing ]
    environment: Testing
    strategy:
      matrix:
        changes: ${{ fromJson(needs.compute-changes.outputs.changes).apps }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        if: ${{ matrix.changes.hasInfrastructure }}
        with:
          terraform_version: 1.1.2
      - uses: actions/download-artifact@v2
        with:
          name: build-${{ matrix.changes.name }}
          path: ${{ matrix.changes.codebasePath }}/build
      - run: ${{ matrix.changes.commandPrefix }} install
        working-directory: ${{ matrix.changes.codebasePath }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}
          TF_STATE_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: ${{ matrix.changes.commandPrefix }} deploy
        working-directory: ${{ matrix.changes.codebasePath }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}/${{ matrix.changes.name }}.tfstate
          TF_STATE_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_VAR_environment: ${{ secrets.ENVIRONMENT }}
          TF_VAR_system: ${{ secrets.SYSTEM }}
