name: Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: ['*']

jobs:
  compute-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.result }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v5
        id: changes
        with:
          script: return await require('./.github/workflows/scripts/build-matrix.js')({github, context});

  test:
    runs-on: ubuntu-latest
    name: 'Tests: ${{ matrix.changes.name }}'
    needs: [ compute-changes ]
    strategy:
      matrix:
        changes: ${{ fromJson(needs.compute-changes.outputs.changes) }}
    steps:
      - uses: actions/checkout@v2
      - run: ${{ matrix.changes.commandPrefix }} install
        working-directory: ${{ matrix.changes.codebasePath }}
      - run: ${{ matrix.changes.commandPrefix }} test
        working-directory: ${{ matrix.changes.codebasePath }}
