name: Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: ['*']

jobs:
  compute-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.result }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v5
        id: changes
        with:
          script: |
            return await require('./.github/workflows/scripts/build-matrix.js')({github, context});

  test:
    runs-on: ubuntu-latest
    needs: [ compute-changes ]
    strategy:
      matrix: ${{ fromJson(needs.compute-changes.outputs.changes) }}
    steps:
      - uses: actions/checkout@v2
      - run: ${{ matrix.commandPrefix }} install
        working-directory: ${{ matrix.path }}
      - run: ${{ matrix.commandPrefix }} test
        working-directory: ${{ matrix.path }}
