name: Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: ['*']

jobs:
  compute-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.result }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v5
        id: changes
        with:
          script: return await require('./.github/workflows/scripts/build-matrix.js')({github, context});

  test:
    runs-on: ubuntu-latest
    name: 'Tests: ${{ matrix.changes.name }}'
    needs: [ compute-changes ]
    strategy:
      matrix:
        changes: ${{ fromJson(needs.compute-changes.outputs.changes).all }}
    steps:
      - uses: actions/checkout@v2
      - run: ${{ matrix.changes.commandPrefix }} install
        working-directory: ${{ matrix.changes.codebasePath }}
      - run: ${{ matrix.changes.commandPrefix }} test
        working-directory: ${{ matrix.changes.codebasePath }}

  lint:
    runs-on: ubuntu-latest
    name: 'Linting: ${{ matrix.changes.name }}'
    needs: [ compute-changes ]
    strategy:
      matrix:
        changes: ${{ fromJson(needs.compute-changes.outputs.changes).all }}
    steps:
      - uses: actions/checkout@v2
      - run: ${{ matrix.changes.commandPrefix }} install
        working-directory: ${{ matrix.changes.codebasePath }}
      - run: ${{ matrix.changes.commandPrefix }} lint
        working-directory: ${{ matrix.changes.codebasePath }}

  build:
    runs-on: ubuntu-latest
    name: 'Build: ${{ matrix.changes.name }}'
    needs: [ compute-changes ]
    strategy:
      matrix:
        changes: ${{ fromJson(needs.compute-changes.outputs.changes).all }}
    steps:
      - uses: actions/checkout@v2
      - run: ${{ matrix.changes.commandPrefix }} install
        working-directory: ${{ matrix.changes.codebasePath }}
      - run: ${{ matrix.changes.commandPrefix }} build
        working-directory: ${{ matrix.changes.codebasePath }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.changes.name }}
          path: ${{ matrix.changes.codebasePath }}/build/**
          if-no-files-found: ignore

  deploy-infra-testing:
    runs-on: ubuntu-latest
    name: 'Deploy Infrastructure (Testing)'
    needs: [ test, build, lint ]
    environment: Testing
    if: ${{ fromJson(needs.compute-changes.outputs.changes).infrastructure }}
    steps:
      - uses: actions/checkout@v2
      - run: ${{ matrix.changes.commandPrefix }} install
        working-directory: ${{ fromJson(needs.compute-changes.outputs.changes).infrastructure.codebasePath }}
      - run: ${{ matrix.changes.commandPrefix }} deploy
        working-directory: ${{ fromJson(needs.compute-changes.outputs.changes).infrastructure.codebasePath }}
