name: Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: ['*']

jobs:
  compute-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v5
        id: changes
        with:
          script: |
            return await require('./.github/workflows/scripts/build-matrix.js')({github, context});
      - run: echo "${{steps.changes.outputs.result}}"
